name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  docker_push:
    name: "Push docker image"
    uses: "philipcristiano/workflows/.github/workflows/docker-build-push.yml@main"
    needs: [flake, rust]
    with:
      repository: ${{ github.repository }}
      timeout: 25

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  rust:
    name: Rust With Postgres 18
    uses: "philipcristiano/workflows/.github/workflows/rust_with_postgres.yml@main"
    with:
      db_image: "postgres:18"
      db_name: et
      db_user: et
      db_password: et

  rust_postgres_17:
    name: Rust With Postgres 17
    uses: "philipcristiano/workflows/.github/workflows/rust_with_postgres.yml@main"
    with:
      db_name: et
      db_user: et
      db_password: et

  rust_postgres_16:
    name: Rust With Postgres 16
    uses: "philipcristiano/workflows/.github/workflows/rust_with_postgres.yml@main"
    with:
      db_name: et
      db_user: et
      db_password: et


  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        SQLX_OFFLINE=true cargo build

  rust_release:
    uses: "philipcristiano/workflows/.github/workflows/rust_release.yml@main"
    needs: [flake, rust]
    secrets:
      WF_GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
